### ISSUE TITLE
ImpersonateLink return error

### ISSUE THREAD

**Issue by imknight** [phpsa/filament-authentication#47] opened 2024-01-10 09:14 UTC
The return type of ImpersonateLink:: impersonate() is wrong, getting this error
"Phpsa\FilamentAuthentication\Actions\ImpersonateLink::impersonate(): Return value must be of type Livewire\Redirector|Illuminate\Http\RedirectResponse|bool, Livewire\Features\SupportRedirects\Redirector returned"

**Comment by chrispian** [comment] 2024-01-11 21:03
Having the same issue. Haven't found the root cause yet. I looked at Impersonate, nothing in their issues at the moment related to this. 

@imknight Are you using SSO or any other special login with yours? We are using SSO and I'm not sure if impersonate broke with SSO or with the latest updates (Laravel 10, Filament 3, Livewire 3, etc.)

I'm working on this issue myself now trying to figure it out.

**Comment by imknight** [comment] 2024-01-12 02:58
I was able to replace action with my own action, but now I've hit another roadblock. It seems that a specific part is still using the Filament v2 config method, and I think the impersonate feature is broken. I replaced it with another impersonate package, which you can find at https://github.com/stechstudio/filament-impersonate.

**Comment by chrispian** [comment] 2024-01-12 14:12
Thanks, I saw that package too. I'll swap them out and go from there. Good find.

**Comment by chrispian** [comment] 2024-01-12 17:20
@imknight Since the UserResource is part of this plugin, did you end up creating your own so you could add the action to the table there? Or can you add an action to a resource another way (I'm looking into both right now). If I switch to the other plugin it seems to require manually adding things in a few places including the table action and edit user resource, etc. So just curious if you found a way add to the one here or did you go all custom?

**Comment by chrispian** [comment] 2024-01-12 17:33
FYI, I just went with creating my own resource. Works great. Thanks for the tip on that plugin. We use Impersonate to debug user issues and confirm permissions, views, etc. all the time.

**Comment by imknight** [comment] 2024-01-13 02:45
@chrispian  ya, using my own user resource, I added the action from the package. Since the only way to impersonate is through the user list, it's not a problem for me.

**Comment by phpsa** [comment] 2024-01-15 21:19
Will be invesigatingf this this week

**Comment by chrispian** [comment] 2024-01-16 14:48
@imknight That's what I ended up doing too. 

@phpsa I'm happy to test once you get something ready. I appreciate you adding the ability to override that easily too. I'll switch back to yours once it's sorted. If I get time this week I'll try to dig around and see what's going on too.

**Closed as completed** 2024-02-10 23:23 UTC
